"""add role to users table

Revision ID: 924cbe3ca7f4
Revises: 97f89f3901ea
Create Date: 2025-03-25 06:51:48.718811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '924cbe3ca7f4'
down_revision: Union[str, None] = '97f89f3901ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_accounts', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_accounts', 'role')
    # ### end Alembic commands ###
